### ISSUE TITLE
postgresql: spec.type needs to be defined, but missing in values.yaml

### ISSUE THREAD

**Issue by Schnitzel** [amazeeio/dbaas-operator#28]
I'm not sure if `spec.type` of `PostgreSQLProvider` is needed or not, but it's not in values.yaml, if you try to apply a values without it there is an error:
```
  Error: UPGRADE FAILED: failed to create resource: PostgreSQLProvider.postgres.amazee.io "production" is invalid: spec.type: Invalid value: "null": spec.type in body must be of type string: "null"
```

**Comment by tobybellwood** [comment]
ah yes, worked through this the other day - it does need to be there, but the only `type` that's actually acted on is for `azure`.  I think there was a fix on the way.  FWIW I set the `type: local` for CI testing

**Comment by tobybellwood** [comment]
it's not required in the MariaDBProviderSpec (https://github.com/amazeeio/dbaas-operator/blob/master/charts/dbaas-operator/templates/mariadb-crd.yaml#L34-L50), but is in the PostgrSQLProviderSpec https://github.com/amazeeio/dbaas-operator/blob/master/charts/dbaas-operator/templates/postgres-crd.yaml#L120-L138 (along with a couple other differences)

**Comment by shreddedbacon** [comment]
Yeah, I have a fix for this pending in this branch https://github.com/amazeeio/dbaas-operator/tree/chart-fixes but it is currently broken

**Comment by tobybellwood** [comment]
Fixed again - just a transient missing go dep
