### ISSUE TITLE
metadata.name: Invalid value must be no more than 63 characters

### ISSUE THREAD

**Issue by vincenzodnp** [amazeeio/dbaas-operator#37]
Today I've got some errors like this because the name of the service was longer than 63 chars
`"Service \"readreplica-drupalexample-database-062bf28d-04fa-47f7-918a-7d149a76770b\" is invalid: metadata.name: Invalid value: \"readreplica-drupalexample-database-062bf28d-04fa-47f7-918a-7d149a76770b\": must be no more than 63 characters"} `

**Comment by shreddedbacon** [comment]
This was fixed in https://github.com/amazeeio/dbaas-operator/pull/25/files but I don't think there has been a release that contains this fix yet.

Will look at the current branch status and see if we can get a release out at some point soon.

**Comment by shreddedbacon** [comment]
Yes, this fix is in v0.1.6 of the dbaas-operator. Updating the cluster to the latest chart version (v0.1.9) will fix that.
